### ISSUE TITLE
make the map 100% big and put the table into a float

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold.github.io#25] opened 2018-06-13 16:14 UTC
Let's put the Google map to the full page, 100% width and height. The list of nodes should go left, into a float. When on mobile, the map should disappear and the list should be 100% width.

**Comment by 0crat** [comment] 2018-06-13 16:16
Job [#25](https://github.com/zold-io/zold.github.io/issues/25) is now in scope, role is `DEV`

**Comment by 0crat** [comment] 2018-06-13 16:18
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment] 2018-06-17 21:41
The job [#25](https://github.com/zold-io/zold.github.io/issues/25) assigned to @blackout314[/z](https://www.0crat.com/u/blackout314), here is [why](https://www.0crat.com/footprint/CAZUFVA8H/1682159105); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by yegor256** [comment] 2018-06-18 08:44
@blackout314 description changed

**Comment by 0crat** [comment] 2018-06-23 09:37
@blackout314[/z](https://www.0crat.com/u/blackout314) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment] 2018-06-25 06:59
@rultor release, tag is `0.3.5`

**Comment by yegor256** [comment] 2018-06-25 07:10
@blackout314 it's possible to move the map outside of the screen. I believe it's possible prevent this from happening:

<img width="1148" alt="screen shot 2018-06-25 at 10 08 45 am" src="https://user-images.githubusercontent.com/526301/41835329-dc323716-785f-11e8-8edb-4f0d6c410918.png">

Also, no mobile the gray area has unequal borders on top, left, and right:

![img_1417](https://user-images.githubusercontent.com/526301/41835351-f209d95e-785f-11e8-918f-d0a8d315e444.PNG)

Also, I think it would be better if we make the table `width:100%`

**Comment by blackout314** [comment] 2018-06-25 07:59
@yegor256 for mobile, ok
for map, the problem is the zoom

**Comment by blackout314** [comment] 2018-06-25 12:38
@yegor256 i'll open another PR

**Comment by 0crat** [comment] 2018-06-27 21:46
The user @blackout314[/z](https://www.0crat.com/u/blackout314) resigned from [#25](https://github.com/zold-io/zold.github.io/issues/25), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment] 2018-06-27 21:46
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @blackout314[/z](https://www.0crat.com/u/blackout314)

**Closed** 2018-11-01 06:02 UTC
Labels: bug, scope

**Comment by 0crat** [comment] 2018-11-01 06:20
Job `gh:zold-io/zold.github.io#25` is not assigned, can't get performer

**Comment by 0crat** [comment] 2018-11-01 06:21
The job [#25](https://github.com/zold-io/zold.github.io/issues/25) is now out of scope
